#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# ES-DE-Plus — written for ES-DE-Plus against public dependency build interfaces.
# Build arm64-v8a or x86_64 with the D-001 NDK; all output is ignored.
set -euo pipefail
[[ -f .clang-format ]] || { echo 'Run from the repository root'; exit 1; }
abi=${1:?Specify arm64-v8a or x86_64}
case $abi in
    arm64-v8a) triple=aarch64-linux-android; openssl_arch=android-arm64; ffarch=aarch64; cpu=armv8-a ;;
    x86_64) triple=x86_64-linux-android; openssl_arch=android-x86_64; ffarch=x86_64; cpu=x86-64 ;;
    *) echo "Unsupported ABI: $abi"; exit 1 ;;
esac
root=$PWD
ndk=${ANDROID_NDK_HOME:?Set ANDROID_NDK_HOME to NDK 28.2.13676358}
grep -q 'Pkg.Revision = 28.2.13676358' "$ndk/source.properties"
case $(uname -s) in Linux) host=linux-x86_64 ;; Darwin) host=darwin-x86_64 ;; *) exit 1 ;; esac
toolbin=$ndk/toolchains/llvm/prebuilt/$host/bin
export PATH="$toolbin:$PATH"
export CC=$toolbin/${triple}29-clang CXX=$toolbin/${triple}29-clang++
export AR=$toolbin/llvm-ar RANLIB=$toolbin/llvm-ranlib STRIP=$toolbin/llvm-strip
export CFLAGS='-O2 -fPIC' CXXFLAGS='-O2 -fPIC'
export LDFLAGS='-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384'
src=$root/android/.deps/sources
work=$root/android/.deps/build/$abi
prefix=$root/android/.deps/install/$abi
libs=$root/android/libs/$abi
jobs=${JOBS:-2}
mkdir -p "$work" "$prefix" "$libs"
# Preserve the real NDK tools, recording only target builds (not configure probes
# or ICU's native host tools). OpenSSL locates plain clang in the real NDK PATH.
audit_tools=$work/compiler-audit
mkdir -p "$audit_tools"
for tool in "${triple}29-clang" "${triple}29-clang++" llvm-ar llvm-ranlib; do
    printf '#!/usr/bin/env bash\nexec python3 "%s/android/license-tool.py" "%s/%s" "$@"\n' "$root" "$toolbin" "$tool" > "$audit_tools/$tool"
    chmod +x "$audit_tools/$tool"
done
export PATH="$audit_tools:$PATH"
export CC=$audit_tools/${triple}29-clang CXX=$audit_tools/${triple}29-clang++
export AR=$audit_tools/llvm-ar RANLIB=$audit_tools/llvm-ranlib
audit_commands=$work/compiler-commands.jsonl
: > "$audit_commands"
export PKG_CONFIG_LIBDIR=$prefix/lib/pkgconfig PKG_CONFIG_PATH=$prefix/lib/pkgconfig
cm() {
    local name=$1 source=$2; shift 2
    cmake -S "$source" -B "$work/$name" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$ndk/build/cmake/android.toolchain.cmake" \
        -DANDROID_ABI="$abi" -DANDROID_PLATFORM=android-29 -DANDROID_STL=c++_shared \
        -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$prefix" -DCMAKE_PREFIX_PATH="$prefix" \
        -DCMAKE_FIND_ROOT_PATH="$prefix" -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=ON -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS" -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" "$@"
    ESDE_LICENSE_COMMANDS="$audit_commands" cmake --build "$work/$name" --parallel "$jobs"
    cmake --install "$work/$name"
}
# FreeImage's upstream distribution has no portable CMake project. Build its complete
# bundled codec set from the public Makefile.srcs, without modifying downloaded source.
freeimage=$src/freeimage/FreeImage
mkdir -p "$work/freeimage-project"
python3 - "$freeimage" "$work/freeimage-project/CMakeLists.txt" <<'PY'
import pathlib, re, sys
source = pathlib.Path(sys.argv[1])
text = (source / 'Makefile.srcs').read_text().replace('\\\n', ' ')
values = dict(re.findall(r'^(SRCS|INCLUDE)\s*=\s*(.*)$', text, re.M))
files = values['SRCS'].split()
incs = [x[2:] for x in values['INCLUDE'].split() if x.startswith('-I')]
with open(sys.argv[2], 'w') as out:
    out.write('# SPDX-License-Identifier: MIT\n# ES-DE-Plus — generated by the dependency build script.\ncmake_minimum_required(VERSION 3.13)\nproject(FreeImage LANGUAGES C CXX)\nset(CMAKE_CXX_STANDARD 11)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n')
    out.write('add_library(freeimage SHARED\n' + '\n'.join('"'+str(source/x)+'"' for x in files) + ')\n')
    out.write('target_include_directories(freeimage PRIVATE\n' + '\n'.join('"'+str(source/x)+'"' for x in incs) + ')\n')
    out.write('target_compile_definitions(freeimage PRIVATE FREEIMAGE_EXPORTS NO_LCMS __ANSI__ HAVE_UNISTD_H DISABLE_PERF_MEASUREMENT PNG_ARM_NEON_OPT=0)\n')
    out.write('set_source_files_properties("'+str(source/'Source/LibJXR/image/decode/segdec.c')+'" PROPERTIES COMPILE_DEFINITIONS "_byteswap_ulong=__builtin_bswap32")\n')
    out.write('set_source_files_properties("'+str(source/'Source/LibJXR/jxrgluelib/JXRGlueJxr.c')+'" PROPERTIES COMPILE_OPTIONS "-include;wchar.h")\n')
    out.write('target_compile_options(freeimage PRIVATE -Wno-narrowing -fexceptions -fvisibility=hidden)\n')
    out.write('target_link_libraries(freeimage PRIVATE log)\ninstall(TARGETS freeimage LIBRARY DESTINATION lib)\n')
PY
cm freeimage "$work/freeimage-project"
# Build libiconv/libcharset's LGPL libraries, not the unused GPL iconv CLI.
# Top-level all/install/install-lib also build src/srclib, so select library
# targets explicitly and install the configure-generated public header.
mkdir -p "$work/libiconv"
(cd "$work/libiconv"; "$src/libiconv/configure" --host="$triple" --prefix="$prefix" --enable-shared --disable-static
 ESDE_LICENSE_COMMANDS="$audit_commands" make lib/localcharset.h
 ESDE_LICENSE_COMMANDS="$audit_commands" make -C lib -j"$jobs"
 ESDE_LICENSE_COMMANDS="$audit_commands" make -C libcharset install
 ESDE_LICENSE_COMMANDS="$audit_commands" make -C lib install
 install -m 644 include/iconv.h.inst "$prefix/include/iconv.h")
# Only the LGPL runtime ships; GPL msgfmt is a host-side build tool.
mkdir -p "$work/gettext"
(cd "$work/gettext"; "$src/gettext/configure" --host="$triple" --prefix="$prefix" \
    --disable-java --disable-csharp --disable-openmp --disable-curses --disable-libasprintf \
    --with-included-libxml --with-libiconv-prefix="$prefix" --enable-shared --disable-static
 ESDE_LICENSE_COMMANDS="$audit_commands" make -C gettext-runtime/intl -j"$jobs"
 ESDE_LICENSE_COMMANDS="$audit_commands" make -C gettext-runtime/intl install)
# ICU needs native host tools for its data archive before cross-compilation.
hosticu=$root/android/.deps/build/icu-host
if [[ ! -x $hosticu/bin/icupkg ]]; then
    mkdir -p "$hosticu"
    (cd "$hosticu"; env -u CC -u CXX -u AR -u RANLIB -u CFLAGS -u CXXFLAGS -u LDFLAGS \
        "$src/icu/source/configure" --disable-tests --disable-samples --disable-extras
     make -j"$jobs")
fi
mkdir -p "$work/icu"
(cd "$work/icu"; "$src/icu/source/configure" --host="$triple" --prefix="$prefix" \
    --with-cross-build="$hosticu" --enable-static --disable-shared --with-data-packaging=static \
    --disable-tests --disable-samples --disable-extras --disable-icuio
 ESDE_LICENSE_COMMANDS="$audit_commands" make -j"$jobs"; ESDE_LICENSE_COMMANDS="$audit_commands" make install)
cm libpng "$src/libpng" -DPNG_SHARED=ON -DPNG_TESTS=OFF -DPNG_TOOLS=OFF
cm harfbuzz "$src/harfbuzz" -DBUILD_SHARED_LIBS=ON -DHB_BUILD_SUBSET=OFF -DHB_HAVE_FREETYPE=OFF -DHB_HAVE_ICU=OFF
cm freetype "$src/freetype" -DBUILD_SHARED_LIBS=ON -DFT_DISABLE_HARFBUZZ=ON -DFT_DISABLE_BZIP2=ON -DFT_DISABLE_BROTLI=ON
# OpenSSL uses the NDK compiler selected via its Android target.
mkdir -p "$work/openssl"
(cd "$work/openssl"; ANDROID_NDK_ROOT="$ndk" "$src/openssl/Configure" "$openssl_arch" \
    -D__ANDROID_API__=29 --prefix="$prefix" --libdir=lib shared no-tests no-apps -Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384
 ESDE_LICENSE_COMMANDS="$audit_commands" make -j"$jobs"; ESDE_LICENSE_COMMANDS="$audit_commands" make install_sw)
cm curl "$src/curl" -DBUILD_SHARED_LIBS=ON -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF \
    -DCURL_USE_OPENSSL=ON -DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF -DCURL_USE_LIBSSH=OFF \
    -DUSE_NGHTTP2=OFF -DCURL_BROTLI=OFF -DCURL_ZSTD=OFF -DENABLE_ARES=OFF
cm libgit2 "$src/libgit2" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DBUILD_CLI=OFF \
    -DUSE_SSH=OFF -DUSE_HTTPS=OpenSSL -DUSE_BUNDLED_ZLIB=OFF -DUSE_THREADS=ON
cm pugixml "$src/pugixml" -DBUILD_SHARED_LIBS=OFF
cm SDL "$src/SDL" -DSDL_SHARED=ON -DSDL_STATIC=OFF -DSDL_TEST=OFF -DSDL_TESTS=OFF
cm ogg "$src/ogg" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF
cat > "$work/dav1d-cross.ini" <<CROSS
[binaries]
c = '$CC'
cpp = '$CXX'
ar = '$AR'
strip = '$STRIP'
pkg-config = 'pkg-config'
[host_machine]
system = 'android'
cpu_family = '$ffarch'
cpu = '$cpu'
endian = 'little'
[built-in options]
c_args = ['-fPIC']
c_link_args = ['-Wl,-z,max-page-size=16384', '-Wl,-z,common-page-size=16384']
CROSS
meson setup "$work/dav1d" "$src/dav1d" --cross-file "$work/dav1d-cross.ini" \
    --prefix "$prefix" --libdir lib --buildtype release -Denable_tools=false -Denable_tests=false
meson compile -C "$work/dav1d" -j "$jobs"
meson install -C "$work/dav1d"
mkdir -p "$work/ffmpeg"
(cd "$work/ffmpeg"; "$src/ffmpeg/configure" --prefix="$prefix" --target-os=android \
    --arch="$ffarch" --cpu="$cpu" --enable-cross-compile --cc="$CC" --cxx="$CXX" --ar="$AR" \
    --ranlib="$RANLIB" --strip="$STRIP" --enable-shared --disable-static --enable-pic \
    --disable-doc --disable-programs --disable-autodetect --disable-lzma --disable-gpl \
    --disable-nonfree --enable-libdav1d --enable-zlib --extra-cflags="-I$prefix/include" \
    --extra-ldflags="-L$prefix/lib $LDFLAGS" --pkg-config=pkg-config
 ESDE_LICENSE_COMMANDS="$audit_commands" make -j"$jobs"; ESDE_LICENSE_COMMANDS="$audit_commands" make install)
# Retain actual compile/header and link inputs beside the cached install.
python3 android/license-inputs.py capture "$abi" "$ndk"
# Package only the upstream link inputs and recursive non-system DT_NEEDED closure.
python3 android/package-dependencies.py "$prefix/lib" "$libs" "$ndk" "$host" "$triple"
printf 'Built dependency closure for %s (API 29, 16 KiB).\n' "$abi"
