#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# ES-DE-Plus — written for ES-DE-Plus against public dependency build interfaces.
# Build arm64-v8a or x86_64 with the D-001 NDK; all output is ignored.
set -euo pipefail
[[ -f .clang-format ]] || { echo 'Run from the repository root'; exit 1; }
abi=${1:?Specify arm64-v8a or x86_64}
case $abi in
    arm64-v8a) triple=aarch64-linux-android; openssl_arch=android-arm64; ffarch=aarch64; cpu=armv8-a ;;
    x86_64) triple=x86_64-linux-android; openssl_arch=android-x86_64; ffarch=x86_64; cpu=x86-64 ;;
    *) echo "Unsupported ABI: $abi"; exit 1 ;;
esac
root=$PWD
ndk=${ANDROID_NDK_HOME:?Set ANDROID_NDK_HOME to NDK 27.3.13750724}
grep -q 'Pkg.Revision = 27.3.13750724' "$ndk/source.properties"
case $(uname -s) in Linux) host=linux-x86_64 ;; Darwin) host=darwin-x86_64 ;; *) exit 1 ;; esac
toolbin=$ndk/toolchains/llvm/prebuilt/$host/bin
export PATH="$toolbin:$PATH"
export CC=$toolbin/${triple}29-clang CXX=$toolbin/${triple}29-clang++
export AR=$toolbin/llvm-ar RANLIB=$toolbin/llvm-ranlib STRIP=$toolbin/llvm-strip
export CFLAGS='-O2 -fPIC' CXXFLAGS='-O2 -fPIC'
export LDFLAGS='-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384'
src=$root/android/.deps/sources
work=$root/android/.deps/build/$abi
prefix=$root/android/.deps/install/$abi
libs=$root/android/libs/$abi
jobs=${JOBS:-2}
mkdir -p "$work" "$prefix" "$libs"
export PKG_CONFIG_LIBDIR=$prefix/lib/pkgconfig PKG_CONFIG_PATH=$prefix/lib/pkgconfig
cm() {
    local name=$1 source=$2; shift 2
    cmake -S "$source" -B "$work/$name" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$ndk/build/cmake/android.toolchain.cmake" \
        -DANDROID_ABI="$abi" -DANDROID_PLATFORM=android-29 -DANDROID_STL=c++_shared \
        -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$prefix" -DCMAKE_PREFIX_PATH="$prefix" \
        -DCMAKE_FIND_ROOT_PATH="$prefix" -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=ON -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS" -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" "$@"
    cmake --build "$work/$name" --parallel "$jobs"
    cmake --install "$work/$name"
}
autoconf_build() {
    local name=$1; shift
    mkdir -p "$work/$name"
    (cd "$work/$name"; "$src/$name/configure" --host="$triple" --prefix="$prefix" "$@"; make -j"$jobs"; make install)
}
# FreeImage's upstream distribution has no portable CMake project. Build its complete
# bundled codec set from the public Makefile.srcs, without modifying downloaded source.
freeimage=$src/freeimage/FreeImage
mkdir -p "$work/freeimage-project"
python3 - "$freeimage" "$work/freeimage-project/CMakeLists.txt" <<'PY'
import pathlib, re, sys
source = pathlib.Path(sys.argv[1])
text = (source / 'Makefile.srcs').read_text().replace('\\\n', ' ')
values = dict(re.findall(r'^(SRCS|INCLUDE)\s*=\s*(.*)$', text, re.M))
files = values['SRCS'].split()
incs = [x[2:] for x in values['INCLUDE'].split() if x.startswith('-I')]
with open(sys.argv[2], 'w') as out:
    out.write('# SPDX-License-Identifier: MIT\n# ES-DE-Plus — generated by the dependency build script.\ncmake_minimum_required(VERSION 3.13)\nproject(FreeImage LANGUAGES C CXX)\nset(CMAKE_CXX_STANDARD 11)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n')
    out.write('add_library(freeimage SHARED\n' + '\n'.join('"'+str(source/x)+'"' for x in files) + ')\n')
    out.write('target_include_directories(freeimage PRIVATE\n' + '\n'.join('"'+str(source/x)+'"' for x in incs) + ')\n')
    out.write('target_compile_definitions(freeimage PRIVATE FREEIMAGE_EXPORTS NO_LCMS __ANSI__ HAVE_UNISTD_H DISABLE_PERF_MEASUREMENT PNG_ARM_NEON_OPT=0)\n')
    out.write('target_compile_options(freeimage PRIVATE -Wno-narrowing -fexceptions -fvisibility=hidden)\n')
    out.write('target_link_libraries(freeimage PRIVATE log)\ninstall(TARGETS freeimage LIBRARY DESTINATION lib)\n')
PY
cm freeimage "$work/freeimage-project"
autoconf_build libiconv --enable-shared --disable-static
# Only the LGPL runtime ships; GPL msgfmt is a host-side build tool.
mkdir -p "$work/gettext"
(cd "$work/gettext"; "$src/gettext/configure" --host="$triple" --prefix="$prefix" \
    --disable-java --disable-csharp --disable-openmp --disable-curses --disable-libasprintf \
    --with-included-libxml --with-libiconv-prefix="$prefix" --enable-shared --disable-static
 make -C gettext-runtime/intl -j"$jobs"
 make -C gettext-runtime/intl install)
# ICU needs native host tools for its data archive before cross-compilation.
hosticu=$root/android/.deps/build/icu-host
if [[ ! -x $hosticu/bin/icupkg ]]; then
    mkdir -p "$hosticu"
    (cd "$hosticu"; env -u CC -u CXX -u AR -u RANLIB -u CFLAGS -u CXXFLAGS -u LDFLAGS \
        "$src/icu/source/configure" --disable-tests --disable-samples --disable-extras
     make -j"$jobs")
fi
mkdir -p "$work/icu"
(cd "$work/icu"; "$src/icu/source/configure" --host="$triple" --prefix="$prefix" \
    --with-cross-build="$hosticu" --enable-static --disable-shared --with-data-packaging=static \
    --disable-tests --disable-samples --disable-extras --disable-icuio
 make -j"$jobs"; make install)
cm libpng "$src/libpng" -DPNG_SHARED=ON -DPNG_TESTS=OFF -DPNG_TOOLS=OFF
cm harfbuzz "$src/harfbuzz" -DBUILD_SHARED_LIBS=ON -DHB_BUILD_SUBSET=OFF -DHB_HAVE_FREETYPE=OFF -DHB_HAVE_ICU=OFF
cm freetype "$src/freetype" -DBUILD_SHARED_LIBS=ON -DFT_DISABLE_HARFBUZZ=ON -DFT_DISABLE_BZIP2=ON -DFT_DISABLE_BROTLI=ON
cm jpeg "$src/jpeg" -DENABLE_SHARED=ON -DENABLE_STATIC=OFF -DWITH_TURBOJPEG=OFF
cm zstd "$src/zstd/build/cmake" -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_TESTS=OFF -DZSTD_BUILD_SHARED=ON -DZSTD_BUILD_STATIC=OFF
cm tiff "$src/tiff" -DBUILD_SHARED_LIBS=ON -Dtiff-tools=OFF -Dtiff-tests=OFF -Dtiff-contrib=OFF -Dtiff-docs=OFF \
    -Dwebp=OFF -Dlzma=OFF -Djbig=OFF -Dlerc=OFF
cm openjpeg "$src/openjpeg" -DBUILD_SHARED_LIBS=ON -DBUILD_CODEC=OFF -DBUILD_TESTING=OFF
cm poppler "$src/poppler" -DENABLE_UNSTABLE_API_ABI_HEADERS=ON -DENABLE_CPP=ON -DENABLE_UTILS=OFF \
    -DENABLE_QT5=OFF -DENABLE_QT6=OFF -DENABLE_GLIB=OFF -DENABLE_BOOST=OFF -DENABLE_NSS3=OFF \
    -DENABLE_GPGME=OFF -DENABLE_LCMS=OFF -DENABLE_LIBCURL=OFF -DENABLE_LIBTIFF=ON \
    -DENABLE_LIBOPENJPEG=openjpeg2 -DFONT_CONFIGURATION=android -DBUILD_CPP_TESTS=OFF -DBUILD_MANUAL_TESTS=OFF \
    -DBUILD_GTK_TESTS=OFF -DRUN_GPERF_IF_PRESENT=OFF
mkdir -p "$root/android/.deps/layout/poppler-cpp"
cp "$work/poppler/cpp/poppler-version.h" "$root/android/.deps/layout/poppler-cpp/"
# OpenSSL uses the NDK compiler selected via its Android target.
mkdir -p "$work/openssl"
(cd "$work/openssl"; ANDROID_NDK_ROOT="$ndk" "$src/openssl/Configure" "$openssl_arch" \
    -D__ANDROID_API__=29 --prefix="$prefix" --libdir=lib shared no-tests no-apps -Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384
 make -j"$jobs"; make install_sw)
cm curl "$src/curl" -DBUILD_SHARED_LIBS=ON -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF \
    -DCURL_USE_OPENSSL=ON -DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF -DCURL_USE_LIBSSH=OFF \
    -DUSE_NGHTTP2=OFF -DCURL_BROTLI=OFF -DCURL_ZSTD=OFF -DENABLE_ARES=OFF
cm libgit2 "$src/libgit2" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DBUILD_CLI=OFF \
    -DUSE_SSH=OFF -DUSE_HTTPS=OpenSSL -DUSE_BUNDLED_ZLIB=OFF -DUSE_THREADS=ON
cm pugixml "$src/pugixml" -DBUILD_SHARED_LIBS=OFF
cm SDL "$src/SDL" -DSDL_SHARED=ON -DSDL_STATIC=OFF -DSDL_TEST=OFF -DSDL_TESTS=OFF
cm ogg "$src/ogg" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF
cat > "$work/dav1d-cross.ini" <<CROSS
[binaries]
c = '$CC'
cpp = '$CXX'
ar = '$AR'
strip = '$STRIP'
pkg-config = 'pkg-config'
[host_machine]
system = 'android'
cpu_family = '$ffarch'
cpu = '$cpu'
endian = 'little'
[built-in options]
c_args = ['-fPIC']
c_link_args = ['-Wl,-z,max-page-size=16384', '-Wl,-z,common-page-size=16384']
CROSS
meson setup "$work/dav1d" "$src/dav1d" --cross-file "$work/dav1d-cross.ini" \
    --prefix "$prefix" --libdir lib --buildtype release -Denable_tools=false -Denable_tests=false
meson compile -C "$work/dav1d" -j "$jobs"
meson install -C "$work/dav1d"
mkdir -p "$work/ffmpeg"
(cd "$work/ffmpeg"; "$src/ffmpeg/configure" --prefix="$prefix" --target-os=android \
    --arch="$ffarch" --cpu="$cpu" --enable-cross-compile --cc="$CC" --cxx="$CXX" --ar="$AR" \
    --ranlib="$RANLIB" --strip="$STRIP" --enable-shared --disable-static --enable-pic \
    --disable-doc --disable-programs --disable-autodetect --disable-lzma --disable-gpl \
    --disable-nonfree --enable-libdav1d --enable-zlib --extra-cflags="-I$prefix/include" \
    --extra-ldflags="-L$prefix/lib $LDFLAGS" --pkg-config=pkg-config
 make -j"$jobs"; make install)
# Android loaders resolve unversioned SONAMEs. Upstream projects select those on Android;
# copy the actual file content, never dangling version symlinks, into the APK input.
python3 - "$prefix/lib" "$libs" "$ndk" "$host" "$triple" <<'PY'
import pathlib, shutil, sys
source, target = map(pathlib.Path, sys.argv[1:3])
for library in source.glob('*.so*'):
    if library.is_file():
        shutil.copyfile(library, target / library.name)
for name in ('libicudata.a', 'libicui18n.a', 'libicuuc.a', 'libpugixml.a'):
    shutil.copyfile(source / name, target / name)
shutil.copyfile(pathlib.Path(sys.argv[3]) / 'toolchains/llvm/prebuilt' / sys.argv[4] / 'sysroot/usr/lib' / sys.argv[5] / 'libc++_shared.so', target / 'libc++_shared.so')
PY
printf 'Built dependency closure for %s (API 29, 16 KiB).\n' "$abi"
